(setq erlang-root-dir "/usr/local/lib/erlang")
(defun load-erlang-from-homebrew ()
  (when (file-accessible-directory-p erlang-root-dir)
    (message "erlang-root-dir is accessible")
    (let* ((erlang-lib-dir (concat erlang-root-dir "/lib"))
           (default-directory erlang-lib-dir)
           (tools-dir (car (file-expand-wildcards "tools-*"))))
      (message "tools-dir: %S" tools-dir)
      (setq load-path (cons (concat erlang-lib-dir "/" tools-dir "/emacs") load-path))
      (message "load-path: %S" load-path)
      (setq exec-path (cons (concat erlang-root-dir "/bin") exec-path))
      (require 'erlang-start))))
(load-erlang-from-homebrew)

(provide 'erlang-config)
